@startuml

abstract class Playlists {
}

abstract class Users {
}
abstract class Videos {
}

abstract class Utilities {
}


abstract class GlobalVariables {
}
abstract class Database {
}

abstract class Comments {
}



@enduml